apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstanceLifecycleConfig
metadata:
  name: wooe
spec:
  notebookInstanceLifecycleConfigName: wooe
  # role: arn:aws:iam::475866477710:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
  onCreate:
    - content: "pipwidddd"
  onStart:
    - content: "pipwfgdfdggdfu"
  # onCreate:
  #          -  |
  #                     wget http://mirrors.ctan.org/macros/latex/contrib/upquote.zip

  #                     EOF
  # onStart:
  #         - content: |
  #                     set -e

  #                     sudo -u ec2-user -i <<'EOF'
  #                     PACKAGE=scipy
  #                     for env in base /home/ec2-user/anaconda3/envs/*; do
  #                         source /home/ec2-user/anaconda3/bin/activate $(basename "$env")
  #                         if [ $env = 'JupyterSystemEnv' ]; then
  #                             continue
  #                         fi
  #                         pip install --upgrade "$PACKAGE"
  #                         source /home/ec2-user/anaconda3/bin/deactivate
  #                     done
  #                     EOF
