apiVersion: sagemaker.aws.amazon.com/v1
kind: TrainingJob
metadata:
  name: xgboost2
spec:
  hyperParameters:
    - name: max_depth
      value: "5"
    - name: eta
      value: "0.2"
    - name: gamma
      value: "4"
    - name: min_child_weight
      value: "6"
    - name: silent
      value: "0"
    - name: objective
      value: multi:softmax
    - name: num_class
      value: "10"
    - name: num_round
      value: "10"
  algorithmSpecification:
    trainingImage: 825641698319.dkr.ecr.us-east-2.amazonaws.com/xgboost:1
    trainingInputMode: File
  roleArn: arn:aws:iam::475866477710:role/ack-sagemaker-execution-role
  region: us-east-2
  outputDataConfig:
    s3OutputPath: s3://training-test-abash/
  resourceConfig:
    instanceCount: 1
    instanceType: ml.m4.xlarge
    volumeSizeInGB: 5
  stoppingCondition:
    maxRuntimeInSeconds: 86400
  inputDataConfig:
    - channelName: train
      dataSource:
        s3DataSource:
          s3DataType: S3Prefix
          s3Uri: s3://training-test-abash/bSV.csv
          s3DataDistributionType: FullyReplicated
      contentType: csv
      compressionType: None
  tags:
    - key: tagKey
      value: tagValue

