apiVersion: sagemaker.services.k8s.aws/v1alpha1
kind: NotebookInstanceLifecycleConfig
metadata:
  name: <YOUR LIFECYCLE CONFIG NAME>
spec:
  notebookInstanceLifecycleConfigName: <YOUR LIFECYCLE CONFIG NAME>
  onStart:
    - content: ZWNobyAiRW50ZXJpbmcgb25TdGFydCI=
  onCreate:
    - content: ZWNobyAiRW50ZXJpbmcgb25DcmVhdGUi