// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package presigned_notebook_instance_url

import (
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.NotebookInstanceName, b.ko.Spec.NotebookInstanceName) {
		delta.Add("Spec.NotebookInstanceName", a.ko.Spec.NotebookInstanceName, b.ko.Spec.NotebookInstanceName)
	} else if a.ko.Spec.NotebookInstanceName != nil && b.ko.Spec.NotebookInstanceName != nil {
		if *a.ko.Spec.NotebookInstanceName != *b.ko.Spec.NotebookInstanceName {
			delta.Add("Spec.NotebookInstanceName", a.ko.Spec.NotebookInstanceName, b.ko.Spec.NotebookInstanceName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SessionExpirationDurationInSeconds, b.ko.Spec.SessionExpirationDurationInSeconds) {
		delta.Add("Spec.SessionExpirationDurationInSeconds", a.ko.Spec.SessionExpirationDurationInSeconds, b.ko.Spec.SessionExpirationDurationInSeconds)
	} else if a.ko.Spec.SessionExpirationDurationInSeconds != nil && b.ko.Spec.SessionExpirationDurationInSeconds != nil {
		if *a.ko.Spec.SessionExpirationDurationInSeconds != *b.ko.Spec.SessionExpirationDurationInSeconds {
			delta.Add("Spec.SessionExpirationDurationInSeconds", a.ko.Spec.SessionExpirationDurationInSeconds, b.ko.Spec.SessionExpirationDurationInSeconds)
		}
	}

	return delta
}
